services:
  user-service:
    build:
      context: ..
      dockerfile: user-service/Dockerfile
    ports:
      - "8002:8000"  # Using port 8002 to avoid conflict with existing services
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./test.db
      - AUTH_SERVICE_URL=http://host.docker.internal:8001  # Assuming auth-service runs on this URL
      - RABBITMQ_URL=amqp://guest:guest@host.docker.internal:5672/  # Assuming RabbitMQ runs on this URL
    volumes:
      - .:/app